export const SET_USER = "SET_USER";
export const SET_LOADER = "SET_LOADER";
export const SET_PATIENT_DATA = "SET_PATIENT_DATA";
export const SET_ERROR = "SET_ERROR";
export const SET_ERROR_MSG = "SET_ERROR_MSG";
export const SET_OTP_ERROR = "SET_OTP_ERROR";
export const LOAD_SPECIALITIES = "LOAD_SPECIALITIES";
export const SET_NEW_USER = "SET_NEW_USER";
export const HANDLE_BACK = "HANDLE_BACK";
export const SET_RESET_DATA = "SET_RESET_DATA";
export const SET_EMAIL_VALID = "SET_EMAIL_VALID";
export const SET_IS_USER_EXSIST = "SET_IS_USER_EXSIST";
export const SET_MAX_ATTEMPT = "SET_MAX_ATTEMPT";
export const SET_ANOTHER_WAY_OTP_FIELD = "SET_ANOTHER_WAY_OTP_FIELD";

//appointments
export const SET_SPECIALITIES = "SET_SPECIALITIES";
export const SET_SELECTED_PROVIDER_DETAILS = "SET_SELECTED_PROVIDER_DETAILS"
export const SET_CLINIC_LIST = "SET_CLINIC_LIST"

//Provider
export const SET_PROVIDER_DETAILS = "SET_PROVIDER_DETAILS";
export const SET_PROVIDER_LIST = "SET_PROVIDER_LIST";

//menu
export const SET_ACTIVE_MENU = "SET_ACTIVE_MENU"

